### ISSUE TITLE
Differing results

### ISSUE THREAD

**Issue by flightsurvey** [adammertel/Leaflet.MarkerCluster.PlacementStrategies#3] opened 2018-11-23 00:53 UTC
Hi,

I've implemented this excellent plugin twice in the same system and one works whilst the other doesn't. By that, I mean that one makes the sub-markers apparent on a circle helper whilst the other just zooms in to make the sub markers visible.

As far as I can see both implementations are more or less identical but with one difference in that the one that doesn't work is first viewed from a very low zoom level showing a whole country in the view port. Can you suggest any changes to the parameters which might solve this?

Cheers, Paddy.

**Comment by adammertel** [comment] 2018-11-30 07:46
Hi Paddy, 
Sorry for such a late response. This problem seems to be more related to the original Leaflet.MarkerCluster library than this PlacementStrategies subplugin - try to turn the subplugin off and see whether the problem remained...

But from what have you described, this looks like a correct behavior (not a bug) - the map would prefer to zoom in before clustering/spiderfying markers, but that depends on your settings. Try to check parameters `zoomToBoundsOnClick`, `spiderfyOnMaxZoom`, `disableClusteringAtZoom` on markerClusterGroup instance and the `maxZoom` on map instance.

Good luck and let me know, whether this helped...
Adam

**Comment by adammertel** [comment] 2018-12-21 19:22
Paddy, I am closing this issue. If the problem still remains, feel free to reopen...

**Closed as completed by adammertel** 2018-12-21 19:22 UTC
